### ISSUE TITLE
Invite me to the GitHub  Organization

### ISSUE THREAD

**Issue by jishanshaikh4** [Coders-Evoke-Community/support#52]
Please invite me to the Coders Evoke Github Organisation ! 

- #### Name: Jishan Shaikh

- #### Discord Username(if exists): jishanshaikh4

- #### Additional Context: Public GitHub profile.

Maybe help with repositories and code one or two.

**Comment by jishanshaikh4** [comment]
Close the issue if you don't me to join /:heart:

**Comment by Ayan-thecodeking** [comment]
> Close the issue if you don't me to join /❤️

hey @jishanshaikh4 now we have resolved the issue ...kindly try again if u want to join and let me know about the issue resolved or not
thank you :)
