### ISSUE TITLE
Invite me to the GitHub Organization

### ISSUE THREAD

**Issue by jishanshaikh4** [Coders-Evoke-Community/support#55]
Please invite me to the Coders Evoke Github Organisation ! 

- #### Name: Jishan Shaikh

- #### Discord Username(if exists): jishanshaikh4

- #### Additional Context:

**Comment by jishanshaikh4** [comment]
@Ayan-thecodeking No, it's not working. Update your invitation.yml file

**Comment by Ayan-thecodeking** [comment]
now u can check @jishanshaikh4 ....now all up to date
